import { StringValueObject } from "@juandardilag/value-objects";

export class Currency extends StringValueObject {
	constructor(value: string) {
		super(value.toUpperCase());
		if (!Currency.isValidCurrencyCode(this.value)) {
			throw new Error(`Invalid currency code: ${this.value}`);
		}
	}

	get symbol(): string {
		return currencies[this.value]?.symbol ?? "$";
	}

	static getCurrenciesCodes(): string[] {
		return Object.keys(currencies);
	}

	static isValidCurrencyCode(code: string): boolean {
		return this.getCurrenciesCodes().includes(code);
	}
}

export const currencies: Record<string, { name: string; symbol?: string }> = {
	AED: { name: "UAE Dirham" },
	AFN: { name: "Afghan Afghani" },
	ALL: { name: "Albanian Lek" },
	AMD: { name: "Armenian Dram" },
	ANG: { name: "Netherlands Antillian Guilder" },
	AOA: { name: "Angolan Kwanza" },
	ARS: { name: "Argentine Peso" },
	AUD: { name: "Australian Dollar" },
	AWG: { name: "Aruban Florin" },
	AZN: { name: "Azerbaijani Manat" },
	BAM: { name: "Bosnia and Herzegovina Convertible Mark" },
	BBD: { name: "Barbados Dollar" },
	BDT: { name: "Bangladeshi Taka" },
	BGN: { name: "Bulgarian Lev" },
	BHD: { name: "Bahraini Dinar" },
	BIF: { name: "Burundian Franc" },
	BMD: { name: "Bermudian Dollar" },
	BND: { name: "Brunei Dollar" },
	BOB: { name: "Bolivian Boliviano" },
	BRL: { name: "Brazilian Real" },
	BSD: { name: "Bahamian Dollar" },
	BTN: { name: "Bhutanese Ngultrum" },
	BWP: { name: "Botswana Pula" },
	BYN: { name: "Belarusian Ruble" },
	BZD: { name: "Belize Dollar" },
	CAD: { name: "Canadian Dollar" },
	CDF: { name: "Congolese Franc" },
	CHF: { name: "Swiss Franc" },
	CLF: { name: "Chilean Unidad de Fomento" },
	CLP: { name: "Chilean Peso" },
	CNH: { name: "Offshore Chinese Renminbi" },
	CNY: { name: "Chinese Renminbi" },
	COP: { name: "Colombian Peso" },
	CRC: { name: "Costa Rican Colon" },
	CUP: { name: "Cuban Peso" },
	CVE: { name: "Cape Verdean Escudo" },
	CZK: { name: "Czech Koruna" },
	DJF: { name: "Djiboutian Franc" },
	DKK: { name: "Danish Krone" },
	DOP: { name: "Dominican Peso" },
	DZD: { name: "Algerian Dinar" },
	EGP: { name: "Egyptian Pound" },
	ERN: { name: "Eritrean Nakfa" },
	ETB: { name: "Ethiopian Birr" },
	EUR: { name: "Euro", symbol: "€" },
	FJD: { name: "Fiji Dollar" },
	FKP: { name: "Falkland Islands Pound" },
	FOK: { name: "Faroese Kr\u00f3na" },
	GBP: { name: "Pound Sterling", symbol: "£" },
	GEL: { name: "Georgian Lari" },
	GGP: { name: "Guernsey Pound" },
	GHS: { name: "Ghanaian Cedi" },
	GIP: { name: "Gibraltar Pound" },
	GMD: { name: "Gambian Dalasi" },
	GNF: { name: "Guinean Franc" },
	GTQ: { name: "Guatemalan Quetzal" },
	GYD: { name: "Guyanese Dollar" },
	HKD: { name: "Hong Kong Dollar" },
	HNL: { name: "Honduran Lempira" },
	HRK: { name: "Croatian Kuna" },
	HTG: { name: "Haitian Gourde" },
	HUF: { name: "Hungarian Forint" },
	IDR: { name: "Indonesian Rupiah" },
	ILS: { name: "Israeli New Shekel" },
	IMP: { name: "Manx Pound" },
	INR: { name: "Indian Rupee" },
	IQD: { name: "Iraqi Dinar" },
	IRR: { name: "Iranian Rial" },
	ISK: { name: "Icelandic Kr\u00f3na" },
	JEP: { name: "Jersey Pound" },
	JMD: { name: "Jamaican Dollar" },
	JOD: { name: "Jordanian Dinar" },
	JPY: { name: "Japanese Yen" },
	KES: { name: "Kenyan Shilling" },
	KGS: { name: "Kyrgyzstani Som" },
	KHR: { name: "Cambodian Riel" },
	KID: { name: "Kiribati Dollar" },
	KMF: { name: "Comorian Franc" },
	KRW: { name: "South Korean Won" },
	KWD: { name: "Kuwaiti Dinar" },
	KYD: { name: "Cayman Islands Dollar" },
	KZT: { name: "Kazakhstani Tenge" },
	LAK: { name: "Lao Kip" },
	LBP: { name: "Lebanese Pound" },
	LKR: { name: "Sri Lanka Rupee" },
	LRD: { name: "Liberian Dollar" },
	LSL: { name: "Lesotho Loti" },
	LYD: { name: "Libyan Dinar" },
	MAD: { name: "Moroccan Dirham" },
	MDL: { name: "Moldovan Leu" },
	MGA: { name: "Malagasy Ariary" },
	MKD: { name: "Macedonian Denar" },
	MMK: { name: "Burmese Kyat" },
	MNT: { name: "Mongolian T\u00f6gr\u00f6g" },
	MOP: { name: "Macanese Pataca" },
	MRU: { name: "Mauritanian Ouguiya" },
	MUR: { name: "Mauritian Rupee" },
	MVR: { name: "Maldivian Rufiyaa" },
	MWK: { name: "Malawian Kwacha" },
	MXN: { name: "Mexican Peso" },
	MYR: { name: "Malaysian Ringgit" },
	MZN: { name: "Mozambican Metical" },
	NAD: { name: "Namibian Dollar" },
	NGN: { name: "Nigerian Naira" },
	NIO: { name: "Nicaraguan C\u00f3rdoba" },
	NOK: { name: "Norwegian Krone" },
	NPR: { name: "Nepalese Rupee" },
	NZD: { name: "New Zealand Dollar" },
	OMR: { name: "Omani Rial" },
	PAB: { name: "Panamanian Balboa" },
	PEN: { name: "Peruvian Sol" },
	PGK: { name: "Papua New Guinean Kina" },
	PHP: { name: "Philippine Peso" },
	PKR: { name: "Pakistani Rupee" },
	PLN: { name: "Polish Z\u0142oty" },
	PYG: { name: "Paraguayan Guaran\u00ed" },
	QAR: { name: "Qatari Riyal" },
	RON: { name: "Romanian Leu" },
	RSD: { name: "Serbian Dinar" },
	RUB: { name: "Russian Ruble" },
	RWF: { name: "Rwandan Franc" },
	SAR: { name: "Saudi Riyal" },
	SBD: { name: "Solomon Islands Dollar" },
	SCR: { name: "Seychellois Rupee" },
	SDG: { name: "Sudanese Pound" },
	SEK: { name: "Swedish Krona" },
	SGD: { name: "Singapore Dollar" },
	SHP: { name: "Saint Helena Pound" },
	SLE: { name: "Sierra Leonean Leone" },
	SLL: { name: "Sierra Leonean Leone" },
	SOS: { name: "Somali Shilling" },
	SRD: { name: "Surinamese Dollar" },
	SSP: { name: "South Sudanese Pound" },
	STN: { name: "S\u00e3o Tom\u00e9 and Pr\u00edncipe Dobra" },
	SYP: { name: "Syrian Pound" },
	SZL: { name: "Eswatini Lilangeni" },
	THB: { name: "Thai Baht" },
	TJS: { name: "Tajikistani Somoni" },
	TMT: { name: "Turkmenistan Manat" },
	TND: { name: "Tunisian Dinar" },
	TOP: { name: "Tongan Pa\u02bbanga" },
	TRY: { name: "Turkish Lira" },
	TTD: { name: "Trinidad and Tobago Dollar" },
	TVD: { name: "Tuvaluan Dollar" },
	TWD: { name: "New Taiwan Dollar" },
	TZS: { name: "Tanzanian Shilling" },
	UAH: { name: "Ukrainian Hryvnia" },
	UGX: { name: "Ugandan Shilling" },
	USD: { name: "United States Dollar" },
	UYU: { name: "Uruguayan Peso" },
	UZS: { name: "Uzbekistani So'm" },
	VES: { name: "Venezuelan Bol\u00edvar Soberano" },
	VND: { name: "Vietnamese \u0110\u1ed3ng" },
	VUV: { name: "Vanuatu Vatu" },
	WST: { name: "Samoan T\u0101l\u0101" },
	XAF: { name: "Central African CFA Franc" },
	XCD: { name: "East Caribbean Dollar" },
	XCG: { name: "Caribbean Guilder" },
	XDR: { name: "Special Drawing Rights" },
	XOF: { name: "West African CFA franc" },
	XPF: { name: "CFP Franc" },
	YER: { name: "Yemeni Rial" },
	ZAR: { name: "South African Rand" },
	ZMW: { name: "Zambian Kwacha" },
	ZWG: { name: "Zimbabwean Dollar" },
	ZWL: { name: "Zimbabwean Dollar" },
};
